INSERT INTO tb_tipo (nome) VALUES ('grass');
INSERT INTO tb_tipo (nome) VALUES ('poison');
INSERT INTO tb_tipo (nome) VALUES ('fire');
INSERT INTO tb_tipo (nome) VALUES ('water');
INSERT INTO tb_tipo (nome) VALUES ('bug');
INSERT INTO tb_tipo (nome) VALUES ('flying');
INSERT INTO tb_tipo (nome) VALUES ('normal');
INSERT INTO tb_tipo (nome) VALUES ('electric');
INSERT INTO tb_tipo (nome) VALUES ('ground');
INSERT INTO tb_tipo (nome) VALUES ('fairy');
INSERT INTO tb_tipo (nome) VALUES ('fighting');
INSERT INTO tb_tipo (nome) VALUES ('psychic');
INSERT INTO tb_tipo (nome) VALUES ('rock');
INSERT INTO tb_tipo (nome) VALUES ('steel');
INSERT INTO tb_tipo (nome) VALUES ('ice');
INSERT INTO tb_tipo (nome) VALUES ('ghost');
INSERT INTO tb_tipo (nome) VALUES ('dragon');

INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('bulbasaur', 1, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('ivysaur', 1, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('venusaur', 1, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('charmander', 3, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('charmeleon', 3, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('charizard', 3, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('squirtle', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('wartortle', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('blastoise', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('caterpie', 5, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('metapod', 5, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('butterfree', 5, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('weedle', 5, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('kakuna', 5, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('beedrill', 5, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('pidgey', 7, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('pidgeotto', 7, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('pidgeot', 7, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('rattata', 7, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('raticate', 7, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('spearow', 7, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('fearow', 7, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('ekans', 2, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('arbok', 2, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('pikachu', 8, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('raichu', 8, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('sandshrew', 9, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('sandslash', 9, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('nidoran-f', 2, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('nidorina', 2, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('nidoqueen', 2, 9);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('nidoran-m', 2, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('nidorino', 2, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('nidoking', 2, 9);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('clefairy', 10, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('clefable', 10, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('vulpix', 3, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('ninetales', 3, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('jigglypuff', 7, 10);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('wigglytuff', 7, 10);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('zubat', 2, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('golbat', 2, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('oddish', 1, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('gloom', 1, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('vileplume', 1, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('paras', 5, 1);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('parasect', 5, 1);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('venonat', 5, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('venomoth', 5, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('diglett', 9, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('dugtrio', 9, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('meowth', 7, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('persian', 7, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('psyduck', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('golduck', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('mankey', 11, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('primeape', 11, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('growlithe', 3, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('arcanine', 3, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('poliwag', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('poliwhirl', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('poliwrath', 4, 11);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('abra', 12, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('kadabra', 12, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('alakazam', 12, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('machop', 11, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('machoke', 11, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('machamp', 11, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('bellsprout', 1, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('weepinbell', 1, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('victreebel', 1, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('tentacool', 4, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('tentacruel', 4, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('geodude', 13, 9);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('graveler', 13, 9);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('golem', 13, 9);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('ponyta', 3, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('rapidash', 3, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('slowpoke', 4, 12);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('slowbro', 4, 12);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('magnemite', 8, 14);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('magneton', 8, 14);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('farfetchd', 7, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('doduo', 7, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('dodrio', 7, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('seel', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('dewgong', 4, 15);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('grimer', 2, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('muk', 2, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('shellder', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('cloyster', 4, 15);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('gastly', 16, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('haunter', 16, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('gengar', 16, 2);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('onix', 13, 9);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('drowzee', 12, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('hypno', 12, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('krabby', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('kingler', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('voltorb', 8, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('electrode', 8, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('exeggcute', 1, 12);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('exeggutor', 1, 12);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('cubone', 9, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('marowak', 9, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('hitmonlee', 11, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('hitmonchan', 11, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('lickitung', 7, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('koffing', 2, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('weezing', 2, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('rhyhorn', 9, 13);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('rhydon', 9, 13);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('chansey', 7, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('tangela', 1, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('kangaskhan', 7, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('horsea', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('seadra', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('goldeen', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('seaking', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('staryu', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('starmie', 4, 12);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('mr-mime', 12, 10);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('scyther', 5, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('jynx', 15, 12);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('electabuzz', 8, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('magmar', 3, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('pinsir', 5, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('tauros', 7, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('magikarp', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('gyarados', 4, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('lapras', 4, 15);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('ditto', 7, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('eevee', 7, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('vaporeon', 4, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('jolteon', 8, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('flareon', 3, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('porygon', 7, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('omanyte', 13, 4);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('omastar', 13, 4);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('kabuto', 13, 4);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('kabutops', 13, 4);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('aerodactyl', 13, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('snorlax', 7, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('articuno', 15, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('zapdos', 8, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('moltres', 3, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('dratini', 17, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('dragonair', 17, NULL);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('dragonite', 17, 6);
INSERT INTO tb_pokemon (nome, tipo_id, tipo_sec_id) VALUES ('mewtwo', 12, NULL);